package processing.test.simple_attacknid;

/* autogenerated by Processing revision 1283 on 2024-12-12 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import android.content.Intent;
import android.os.Bundle;
import ketai.net.bluetooth.*;
import ketai.ui.*;
import ketai.net.*;
import controlP5.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class simple_attacknid extends PApplet {


//required for BT enabling on startup








ControlP5 cp5;

KetaiBluetooth bt;

String info = "";
KetaiList klist;

boolean isConfiguring = true;
String ctlkey;

//********************************************************************
// The following code is required to enable bluetooth at startup.
//********************************************************************
 public void onCreate(Bundle savedInstanceState) {
  super.onCreate(savedInstanceState);
  //start listening for BT connections
  bt = new KetaiBluetooth(this);
}

 public void onActivityResult(int requestCode, int resultCode, Intent data) {
  bt.onActivityResult(requestCode, resultCode, data);
}

//********************************************************************

 public void setup()
{
  /* size commented out by preprocessor */;
  //orientation(PORTRAIT);
  orientation(LANDSCAPE);
  background(78, 93, 75);
  stroke(255);
  textSize(16*((int)displayDensity));

  bt.start();

  PFont pfont = createFont("Candara", 40, true);
  ControlFont font = new ControlFont(pfont, 12*((int)displayDensity));

  cp5 = new ControlP5(this);
  cp5.setFont(font);

  cp5.addButton("discover")
    .setCaptionLabel("Discover")
    .setPosition(10, 50)
    .setSize(200, 120);

  cp5.addButton("discoverable")
    .setCaptionLabel("Discoverable")
    .setPosition(250, 50)
    .setSize(200, 120);

  cp5.addButton("btconnect")
    .setCaptionLabel("Connect")
    .setPosition(500, 50)
    .setSize(200, 120);

  cp5.addButton("btpair")
    .setCaptionLabel("Paired")
    .setPosition(750, 50)
    .setSize(200, 120);

  cp5.addButton("btinfo")
    .setCaptionLabel("Info")
    .setPosition(1000, 50)
    .setSize(200, 120);

  cp5.addButton("btstop")
    .setCaptionLabel("Stop")
    .setPosition(1250, 50)
    .setSize(200, 120);

  cp5.addButton("btcontrol")
    .setCaptionLabel("Control")
    .setPosition(1500, 50)
    .setSize(200, 120);

  cp5.addButton("btclose")
    .setCaptionLabel("Exit")
    .setPosition(1750, 50)
    .setSize(200, 120);

  cp5.addButton("button1")
    .setCaptionLabel("  fire")
    .setPosition(80, 500)
    .setSize(220, 120);

  cp5.addButton("button2")
    .setCaptionLabel("  left")
    .setPosition(80, 700)
    .setSize(220, 120);
}

 public void draw()
{
  if (isConfiguring == true) {
    ArrayList<String> names;
    background(78, 93, 75);

    //based on last control command  lets display appropriately
    if (ctlkey == "info") {
      info = getBluetoothInformation();
    } else {
      if (ctlkey == "pair") {
        info = "Paired Devices:\n";
        names = bt.getPairedDeviceNames();
      } else {
        info = "Discovered Devices:\n";
        names = bt.getDiscoveredDeviceNames();
      }
      for (int i=0; i < names.size(); i++) {
        info += "["+i+"] "+names.get(i).toString() + "\n";
      }
    }
    textSize(16*((int)displayDensity));
    text(info, 5, 300);
  } else {
    background(78, 93, 75);
  }
}

 public String getBluetoothInformation()
{
  String btInfo = "Server Running: ";
  btInfo += bt.isStarted() + "\n";
  btInfo += "Device Discoverable: "+bt.isDiscoverable() + "\n";
  btInfo += "Device Discovering:" + bt.isDiscovering();
  btInfo += "\nConnected Devices: \n";

  ArrayList<String> devices = bt.getConnectedDeviceNames();
  for (String device : devices) {
    btInfo+= device+"\n";
  }

  return btInfo;
}

 public void onKetaiListSelection(KetaiList klist)
{
  String selection = klist.getSelection();

  if (!selection.equals("CANCEL")) {
    bt.connectToDeviceByName(selection);
  }

  //dispose of list for now
  klist = null;
}

 public void discover() {
  bt.discoverDevices();

  ctlkey = "dis";
  isConfiguring = true;
}

 public void discoverable() {
  bt.makeDiscoverable();
  isConfiguring = true;
}

 public void btconnect() {

  //If we have not discovered any devices, try prior paired devices
  if (bt.getDiscoveredDeviceNames().size() > 0) {
    ArrayList<String> list = bt.getDiscoveredDeviceNames();
    list.add("CANCEL");
    klist = new KetaiList(this, list);
  } else if (bt.getPairedDeviceNames().size() > 0) {
    ArrayList<String> list = bt.getPairedDeviceNames();
    list.add("CANCEL");
    klist = new KetaiList(this, list);
  }
  isConfiguring = true;
}

 public void btpair() {
  ctlkey = "pair";
  isConfiguring = true;
}

 public void btinfo() {
  ctlkey = "info";
  isConfiguring = true;
}

 public void btstop() {
  bt.stop();
}

 public void btcontrol() {
  ctlkey = "ctl";
  isConfiguring = false;
}

 public void btclose() {
  this.getActivity().finish();
}

 public void button1() {
  if (isConfiguring) {
    return;
  }

  byte[] data = {(byte)0x71, (byte)0x00, (byte)0x80, (byte)0x80, (byte)0x80, (byte)0x80, (byte)0x82, (byte)0x88};   //fire
  bt.broadcast(data);
}

 public void button2() {
  if (isConfiguring) {
    return;
  }

  byte[] data = {(byte)0x71, (byte)0x00, (byte)0x80, (byte)0x82, (byte)0x80, (byte)0x80, (byte)0x80, (byte)0x08};   //turn left
  bt.broadcast(data);
}


  public void settings() { fullScreen(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "simple_attacknid" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
